version: "3.8"

services:
  db:
    image: postgres:14
    container_name: barbearia-db
    environment:
      POSTGRES_DB: barbearia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d barbearia_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  api:
    container_name: barbearia-api
    build: .
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Host=db;Database=barbearia_db;Username=postgres;Password=mysecretpassword"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres-data:
